### ISSUE TITLE
running make docker-run-pgstac: cannot import name 'as_shape' from 'pygeoif.geometry'

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-fastapi#467]
The first version of pygeoif 1.0.0 was just released since 2017, so this likely has a breaking change. 

```
wait-for-it.sh: waiting 15 seconds for database:5432
wait-for-it.sh: database:5432 is available after 5 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/stac_fastapi/pgstac/stac_fastapi/pgstac/app.py", line 15, in <module>
    from stac_fastapi.pgstac.core import CoreCrudClient
  File "/app/stac_fastapi/pgstac/stac_fastapi/pgstac/core.py", line 13, in <module>
    from pygeofilter.backends.cql2_json import to_cql2
  File "/usr/local/lib/python3.8/site-packages/pygeofilter/backends/cql2_json/__init__.py", line 1, in <module>
    from .evaluate import to_cql2
  File "/usr/local/lib/python3.8/site-packages/pygeofilter/backends/cql2_json/evaluate.py", line 32, in <module>
    from ..evaluator import Evaluator, handle
  File "/usr/local/lib/python3.8/site-packages/pygeofilter/backends/evaluator.py", line 31, in <module>
    from .. import ast
  File "/usr/local/lib/python3.8/site-packages/pygeofilter/ast.py", line 32, in <module>
    from . import values
  File "/usr/local/lib/python3.8/site-packages/pygeofilter/values.py", line 33, in <module>
    from pygeoif.geometry import as_shape
ImportError: cannot import name 'as_shape' from 'pygeoif.geometry' (/usr/local/lib/python3.8/site-packages/pygeoif/geometry.py)
make: *** [docker-run-pgstac] Error 1
```

**Comment by philvarner** [comment]
I think so, it didn't fail for me when I ran it last week.
