### ISSUE TITLE
Error AttributeError: 'BaseSearchPostRequest' object has no attribute 'conf' when searching STAC API with POST

### ISSUE THREAD

**Issue by alexgleith** [stac-utils/stac-fastapi#609]
I'm attempting a minimum viable STAC API based on PGSTAC, and it works, but... I think the post requests to the search API are failing and I don't know enough about the code to know how to resolve it.

My app code is [here](https://github.com/digitalearthpacific/dep-stac/blob/main/stac_api/app.py), copied below:

```python
settings = Settings()

extensions = [
    FilterExtension(),
    QueryExtension(),
    SortExtension(),
    FieldsExtension(),
    TokenPaginationExtension(),
    ContextExtension(),
]
post_request_model = create_post_request_model(extensions, base_model=PgstacSearch)
get_request_model = create_get_request_model(extensions)

api = StacApi(
    title=title,
    description=description,
    extensions=extensions,
    settings=settings,
    client=CoreCrudClient(post_request_model=post_request_model, landing_page_id=id),
    search_get_request_model=get_request_model,
    response_class=ORJSONResponse,
)

app: FastAPI = api.app
```

And the stack trace for the error I'm getting when using `pystac-client` to query it is here:

```bash
'BaseSearchPostRequest' object has no attribute 'conf'
NoneType: None
INFO:     172.19.0.1:38362 - "POST /search HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/stac_fastapi/api/middleware.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/brotli_asgi/__init__.py", line 81, in __call__
    await br_responder(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/brotli_asgi/__init__.py", line 126, in __call__
    await self.app(scope, receive, self.send_with_brotli)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/stac_fastapi/api/routes.py", line 68, in _endpoint
    await func(request_data, request=request), response_class
  File "/usr/local/lib/python3.10/dist-packages/stac_fastapi/pgstac/core.py", line 339, in post_search
    item_collection = await self._search_base(search_request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/stac_fastapi/pgstac/core.py", line 164, in _search_base
    search_request.conf = search_request.conf or {}
AttributeError: 'BaseSearchPostRequest' object has no attribute 'conf'
```

I'm guessing it's something obvious if you know what you're doing, which I clearly don't!

**Comment by drnextgis** [comment]
`search_post_request_model` is missing:

```python
api = StacApi(
    search_post_request_model=post_request_model,
    ...
)
```

**Comment by alexgleith** [comment]
That's it!

Thank you so much, @drnextgis
